### PR TITLE
Implemented hot backups of the LevelDB database

### PR DESCRIPTION
**Pull request by marksteele**

### CODE REVIEW

**Comment by tatsuya6502** [comment]
Thank you for the pull request! I will review and get back to you.

**Comment by tatsuya6502** [comment]
Thank you very much for your contribution! I have merged your PR to the develop branch.

Please note that I only merged your first commit https://github.com/leveldb-erlang/h2leveldb/commit/b7e84bb3ea0e9e9c3bd25c2424c8b360e655d370, because I do not want to redistribute dependencies. Instead, I updated our local forks of HyperLevelDB and Snappy, and [fixed some problems](https://github.com/leveldb-erlang/h2leveldb/issues/8) in build_deps.sh.

**Comment by marksteele** [comment]
I had bundled the dependencies as I'm building using Basho's node_package code, and the build pipeline breaks. 

Thanks for the merge!

**Comment by tatsuya6502** [comment]
> I had bundled the dependencies as I'm building using Basho's node_package code, and the build pipeline breaks.

Oh, I see. node_package seems an interesting tool, and it supports all OS/distros that I am targeting to (RHEL, FreeBSD and SmartOS). When I have more time, I will try if I can fix the build pipeline without bundling the dependencies.

Thanks,

**Pull request closed without merging**
